name: 'Adding Users to eng-incident'

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'The Github Actions environment to use'
        required: true
        type: string
        default: ruwan-test
      user_id:
        description: 'Email id of the Engineer(s) needs add into eng-incident group'
        required: true
        type: string
        default: "ruwanranganath@hotmail.com"
      skip_worker_utterance_collections:
        description: 'Skip updating worker-utterance-collections'
        required: false
        type: boolean
        default: false
      skip_worker_analytics_forwarding:
        description: 'Skip updating worker-analytics-forwarding'
        required: false
        type: boolean
        default: false
      skip_service_3:
        description: 'Skip updating service_3'
        required: false
        type: boolean
        default: false
      skip_service_4:
        description: 'Skip updating service_4'
        required: false
        type: boolean
        default: false


permissions:
      id-token: write
      contents: read


jobs: 
 build-and-deploy:
  runs-on: ubuntu-latest
  environment: 
  name:  ${{ inputs.environment }}
  steps:
    - name: Azure login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Add user to Azure AD group
      id: adduserentra
      run: |
        USER_ID=$(az ad user list --filter "mail eq '${{ github.event.inputs.user_id }}'" --query "[].id" -o tsv)
        echo "=========="
        az ad user list
        echo "============="
        az ad user list --filter "mail eq '${{ github.event.inputs.user_id }}'" --query "[].id" -o tsv
        echo "================"
        echo "User ID: '$USER_ID'"
        if [ -z "$USER_ID" ]; then
          echo "User not found for email $USER_ID"
          exit 1
        else
          az ad group member add --group ruwan-eng-incident --member-id $USER_ID
        fi
      shell: bash

    # - name: Retrive User ObjectID from Entra
    #   run:  USER_ID=$(az ad user list --filter "mail eq '${{ github.event.inputs.user_id }}'" --query "[].id" -o tsv)
   
    # - name: Add User to Group
    #   id: adduserentra
    #   run: |
    #     if [ -z "$USER_ID" ]; then
    #         echo "User not found for email $USER_ID"
    #         exit 1
    #       else
    #         az ad group member add --group ruwan-eng-incident --member-id $USER_ID
    #       fi

    # - name: Post to a Slack channel eng-mon-incident-group-users
    #   id: slack
    #   uses: slackapi/slack-github-action@v1.25.0
    #   if: steps.adduserentra.outcome == 'success'
    #   with:
    #     channel-id: 'eng-mon-incident-group-users'
    #     slack-message: "New user added to eng-incident group : ${{ github.event.inputs.user_id }}"
    #   env:
    #     SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
