name: 'Adding Users to eng-incident'

on:
  workflow_dispatch:
    inputs:
      user_id:
        description: 'Email id of the Engineer(s) needs add into eng-incident group'
        required: true
        type: string
        default: "ruwanranganath@hotmail.com"


permissions:
      id-token: write
      contents: read


jobs: 
 build-and-deploy:
  runs-on: ubuntu-latest
  steps:
    - name: Azure login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Add user to Azure AD group
      run: |
        USER_ID=$(az ad user list --filter "mail eq '${{ github.event.inputs.user_id }}'" --query "[].id" -o tsv)
        echo "=========="
        az ad user list
        echo "============="
        az ad user list --filter "mail eq '${{ github.event.inputs.user_id }}'" --query "[].id" -o tsv
        echo "================"
        echo "User ID: '$USER_ID'"
        if [ -z "$USER_ID" ]; then
          echo "User not found for email $USER_ID"
          exit 1
        else
          az ad group member add --group ruwan-eng-incident --member-id $USER_ID
        fi
      shell: bash

    # - name: Retrive User ObjectID from Entra
    #   run:  USER_ID=$(az ad user list --filter "mail eq '${{ github.event.inputs.user_id }}'" --query "[].objectId" -o tsv)
   
    # - name: Add User to Group
    #   run:  az ad group member add --group ruwan-eng-incident --member-id $USER_ID

    - name: Post to a Slack channel eng-mon-incident-group-users
      id: slack
      uses: slackapi/slack-github-action@v1.25.0
      if: steps.azuregroup.outcome == 'success'
      with:
        channel-id: 'eng-mon-incident-group-users'
        slack-message: "New user added to eng-incident group : ${{ github.event.inputs.user_id }}"
      env:
        SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
