name: 'workflow for test'

on:
  workflow_dispatch:
    inputs:
      service_names:
        description: 'Service names(s) to update'
        required: true
        type: string
        default: "api,engine,voice-gateway"
      commit_hash:
        description: 'commit hash to update as Image tag'
        required: true
        type: string


jobs:
  first-job:
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ github.token }}  
    steps:
    - id: identify
      run: |

        gh repo view --json defaultBranchRef --jq '.defaultBranchRef.target.oid'
        gh pr list --state open --limit 1 --json number --jq '.[0].number'
        gh pr list --state open --limit 1 --json headRefOid --jq '.[0].headRefOid'

        echo "==============="
        
        # use bash variable expression to get the substring
        export GIT_PR_SHA="${{ github.sha }}"
        export GIT_PR_SHA_SHORT="${GIT_PR_SHA:0:10}"

        echo "::set-output name=git_pr_sha::${GIT_PR_SHA}"
        echo "::set-output name=git_pr_sha_short::${GIT_PR_SHA_SHORT}"
    outputs:
      git_pr_sha: ${{ steps.identify.outputs.git_pr_sha }}
      git_pr_sha_short: ${{ steps.identify.outputs.git_pr_sha_short }}
      
  update-services:
      name: Call PR workflow for each service
      uses: Ruwan-Ranganath/workflows/.github/workflows/reusable-workflow.yaml@main
      with:
        service_names: ${{ github.event.inputs.service_names }}
        tf_workspace: ${{ needs.first-job.outputs.git_pr_sha }}
        commit_hash: ${{ github.event.inputs.commit_hash }}
