name: 'workflow for test'

on:
  workflow_dispatch:
    inputs:
      service_names:
        description: 'Service names(s) to update'
        required: true
        type: string
        default: "api,engine,voice-gateway"
      commit_hash:
        description: 'commit hash to update as Image tag'
        required: true
        type: string


jobs:
  identify:
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ github.token }}  
    steps:
    - uses: actions/checkout@v4
      ref: 'newbranch'
    
    - id: identify
      run: |

        gh repo view --json defaultBranchRef --jq '.defaultBranchRef.target.oid'

        # Capture the latest open PR's head commit SHA
        # PR_HEAD_SHA=$(gh pr list --state open --limit 1 --json headRefOid --jq '.[0].headRefOid')
        # echo "PR_HEAD_SHA=${PR_HEAD_SHA}" >> $GITHUB_OUTPUT

        # echo "${PR_HEAD_SHA}"

        echo "PR_HEAD_SHA=$(gh pr list --state open --limit 1 --json headRefOid --jq '.[0].headRefOid')" >> $GITHUB_OUTPUT


    outputs:
      PR_HEAD_SHA: ${{ steps.identify.outputs.PR_HEAD_SHA }}

      
  update-services:
      name: Call PR workflow for each service
      needs: [identify]
      uses: Ruwan-Ranganath/workflows/.github/workflows/reusable-workflow.yaml@main
      with:
        service_names: ${{ github.event.inputs.service_names }}
        tf_workspace: ${{ needs.identify.outputs.PR_HEAD_SHA }}
        commit_hash: ${{ github.event.inputs.commit_hash }}
