name: 'workflow for test'

on:
  workflow_dispatch:
    inputs:
      service_names:
        description: 'Service names(s) to update'
        required: true
        type: string
        default: "api,engine,voice-gateway"
      commit_hash:
        description: 'commit hash to update as Image tag'
        required: true
        type: string

jobs:
  update-services:
      name: Call PR workflow for each service
      uses: Ruwan-Ranganath/workflows/.github/workflows/reusable-workflow.yaml@main
      with:
        service_names: ${{ github.event.inputs.service_names }}
        tf_workspace: ${{ github.sha }}
        commit_hash: ${{ github.event.inputs.commit_hash }}
