name: 'workflow for test'

on:
  workflow_dispatch:
    inputs:
      service_names:
        description: 'Service names(s) to update'
        required: true
        type: string
        default: "api,engine,voice-gateway"
      commit_hash:
        description: 'commit hash to update as Image tag'
        required: true
        type: string

jobs:
  steps:
    name: Call PR workflow
    uses: Ruwan-Ranganath/workflows/.github/workflows/reusable-workflow.yaml@main
    with:
      service_name: ${{ inputs.service_name }}
      tf_workspace: qe-test
      commit_hash: ${{ inputs.commit_hash }}
